<form class="form products-in-range" id="products_in_range_form" data-mage-init='{
	"validation":{
		"rules": {
			"min_price": {
				"required": true,
        "validate-currency-dollar": true,
        "validate-greater-than-zero": true
			},
      "max_price": {
				"required": true,
        "validate-currency-dollar": true,
        "validate-greater-than-zero": true,
        "validate-price-range": true
			}
		}
	}
}'>
    <div class="field min-price">
        <label class="label" for="min_price" data-role="min-price-label">
            <span><?php echo __('Minimum Price'); ?></span>
        </label>
        <div class="control">
            <input id="min_price"
                   name="min_price"
                   type="text"
                   class="input-text"
                   placeholder="<?php echo __('Minimum price'); ?>" />
        </div>
    </div>
    <div class="field max-price">
        <label class="label" for="max_price" data-role="max-price-label">
            <span><?php echo __('Maximum Price'); ?></span>
        </label>
        <div class="control">
            <input id="max_price"
                   name="max_price"
                   type="text"
                   class="input-text"
                   placeholder="<?php echo __('Maximum price'); ?>" />
        </div>
    </div>
    <div class="actions">
        <button type="submit"
                title="<?php echo $this->escapeHtml(__('Search')) ?>"
                class="action search">
            <span><?php echo __('Search'); ?></span>
        </button>
    </div>
</form>
<div id='validation_errors' class='mage-error'></div>
<script>
require(['jquery',
'mage/mage',
'mage/validation'], function($) {
  $('#products_in_range_form').on('submit', function(e) {
    e.preventDefault();

    // Validate form
    if (!$('#products_in_range_form').validation()
        || !$('#products_in_range_form').validation('isValid')
    ) {
      return false;
    }

    // Load grid data
    $.ajax({
        url: '<?php echo $this->getAjaxGridUrl(); ?>',
        type: 'POST',
        data: $(this).serialize(),
        contentType: 'application/x-www-form-urlencoded',
        showLoader: true,
        beforeSend: function() {
          $('#validation_errors').empty();
        }
    }).done(function(response) {
        if (response.hasOwnProperty('error')) {
            $('#validation_errors').append('<p>' + response.error + '</p>');
        }
    });

  });
});
</script>
